name: zz_blog
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.22.1
  dio: ^2.1.13

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    path: ../../../software/flutter_web/packages/flutter_web
  flutter_web_ui:
    path: ../../../software/flutter_web/packages/flutter_web_ui
